export const COUNTRY_DATA_LIST = [
  {
    name: "Afghanistan",
    callingCode: "+93",
    countryCode_2: "AF",
    countryCode_3: "AFG",
  },
  {
    name: "Albania",
    callingCode: "+355",
    countryCode_2: "AL",
    countryCode_3: "ALB",
  },
  {
    name: "Algeria",
    callingCode: "+213",
    countryCode_2: "DZ",
    countryCode_3: "DZA",
  },
  {
    name: "American Samoa",
    callingCode: "+1684",
    countryCode_2: "AS",
    countryCode_3: "ASM",
  },
  {
    name: "Andorra",
    callingCode: "+376",
    countryCode_2: "AD",
    countryCode_3: "AND",
  },
  {
    name: "Angola",
    callingCode: "+244",
    countryCode_2: "AO",
    countryCode_3: "AGO",
  },
  {
    name: "Anguilla",
    callingCode: "+1264",
    countryCode_2: "AI",
    countryCode_3: "AIA",
  },
  {
    name: "Antarctica",
    callingCode: "+672",
    countryCode_2: "AQ",
    countryCode_3: "ATA",
  },
  {
    name: "Antigua and Barbuda",
    callingCode: "+1268",
    countryCode_2: "AG",
    countryCode_3: "ATG",
  },
  {
    name: "Argentina",
    callingCode: "+54",
    countryCode_2: "AR",
    countryCode_3: "ARG",
  },
  {
    name: "Armenia",
    callingCode: "+374",
    countryCode_2: "AM",
    countryCode_3: "ARM",
  },
  {
    name: "Aruba",
    callingCode: "+297",
    countryCode_2: "AW",
    countryCode_3: "ABW",
  },
  {
    name: "Australia",
    callingCode: "+61",
    countryCode_2: "AU",
    countryCode_3: "AUS",
    states: [
      { name: "Australian Capital Territory", code: "ACT" },
      { name: "New South Wales", code: "NSW" },
      { name: "Northern Territory", code: "NT" },
      { name: "Queensland", code: "QLD" },
      { name: "South Australia", code: "SA" },
      { name: "Tasmania", code: "TAS" },
      { name: "Victoria", code: "VIC" },
      { name: "Western Australia", code: "WA" },
    ],
  },
  {
    name: "Austria",
    callingCode: "+43",
    countryCode_2: "AT",
    countryCode_3: "AUT",
  },
  {
    name: "Azerbaijan",
    callingCode: "+994",
    countryCode_2: "AZ",
    countryCode_3: "AZE",
  },
  {
    name: "Bahamas",
    callingCode: "+1242",
    countryCode_2: "BS",
    countryCode_3: "BHS",
  },
  {
    name: "Bahrain",
    callingCode: "+973",
    countryCode_2: "BH",
    countryCode_3: "BHR",
  },
  {
    name: "Bangladesh",
    callingCode: "+880",
    countryCode_2: "BD",
    countryCode_3: "BGD",
  },
  {
    name: "Barbados",
    callingCode: "+1246",
    countryCode_2: "BB",
    countryCode_3: "BRB",
  },
  {
    name: "Belarus",
    callingCode: "+375",
    countryCode_2: "BY",
    countryCode_3: "BLR",
  },
  {
    name: "Belgium",
    callingCode: "+32",
    countryCode_2: "BE",
    countryCode_3: "BEL",
  },
  {
    name: "Belize",
    callingCode: "+501",
    countryCode_2: "BZ",
    countryCode_3: "BLZ",
  },
  {
    name: "Benin",
    callingCode: "+229",
    countryCode_2: "BJ",
    countryCode_3: "BEN",
  },
  {
    name: "Bermuda",
    callingCode: "+1441",
    countryCode_2: "BM",
    countryCode_3: "BMU",
  },
  {
    name: "Bhutan",
    callingCode: "+975",
    countryCode_2: "BT",
    countryCode_3: "BTN",
  },
  {
    name: "Bolivia",
    callingCode: "+591",
    countryCode_2: "BO",
    countryCode_3: "BOL",
  },
  {
    name: "Bosnia and Herzegovina",
    callingCode: "+387",
    countryCode_2: "BA",
    countryCode_3: "BIH",
  },
  {
    name: "Botswana",
    callingCode: "+267",
    countryCode_2: "BW",
    countryCode_3: "BWA",
  },
  {
    name: "Brazil",
    callingCode: "+55",
    countryCode_2: "BR",
    countryCode_3: "BRA",
    states: [
      {
        name: "Acre",
        code: "AC",
      },
      {
        name: "Alagoas",
        code: "AL",
      },
      {
        name: "Amapa",
        code: "AP",
      },
      {
        name: "Amazonas",
        code: "AM",
      },
      {
        name: "Bahia",
        code: "BA",
      },
      {
        name: "Ceará",
        code: "CE",
      },
      {
        name: "Espirito Santo",
        code: "ES",
      },
      {
        name: "Goias",
        code: "GO",
      },
      {
        name: "Maranhao",
        code: "MA",
      },
      {
        name: "Mato Grosso",
        code: "MT",
      },
      {
        name: "Mato Grosso do Sul",
        code: "MS",
      },
      {
        name: "Minas Gerais",
        code: "MG",
      },
      {
        name: "Para",
        code: "PA",
      },
      {
        name: "Paraiba",
        code: "PB",
      },
      {
        name: "Parana",
        code: "PR",
      },
      {
        name: "Pernambuco",
        code: "PE",
      },
      {
        name: "Piaui",
        code: "PI",
      },
      {
        name: "Rio de Janeiro",
        code: "RJ",
      },
      {
        name: "Rio Grande do Norte",
        code: "RN",
      },
      {
        name: "Rio Grande do Sul",
        code: "RS",
      },
      {
        name: "Rondonia",
        code: "RO",
      },
      {
        name: "Roraima",
        code: "RR",
      },
      {
        name: "Santa Catarina",
        code: "SC",
      },
      {
        name: "Sao Paulo",
        code: "SP",
      },
      {
        name: "Sergipe",
        code: "SE",
      },
      {
        name: "Tocantins",
        code: "TO",
      },
      {
        name: "Ceara",
        code: "CA",
      },
      {
        name: "Distrito Federal",
        code: "DIF",
      },
    ],
  },
  {
    name: "British Indian Ocean Territory",
    callingCode: "+246",
    countryCode_2: "IO",
    countryCode_3: "IOT",
  },
  {
    name: "British Virgin Islands",
    callingCode: "+1284",
    countryCode_2: "VG",
    countryCode_3: "VGB",
  },
  {
    name: "Brunei",
    callingCode: "+673",
    countryCode_2: "BN",
    countryCode_3: "BRN",
  },
  {
    name: "Bulgaria",
    callingCode: "+359",
    countryCode_2: "BG",
    countryCode_3: "BGR",
  },
  {
    name: "Burkina Faso",
    callingCode: "+226",
    countryCode_2: "BF",
    countryCode_3: "BFA",
  },
  {
    name: "Burundi",
    callingCode: "+257",
    countryCode_2: "BI",
    countryCode_3: "BDI",
  },
  {
    name: "Cambodia",
    callingCode: "+855",
    countryCode_2: "KH",
    countryCode_3: "KHM",
  },
  {
    name: "Cameroon",
    callingCode: "+237",
    countryCode_2: "CM",
    countryCode_3: "CMR",
  },
  {
    name: "Canada",
    callingCode: "+1",
    countryCode_2: "CA",
    countryCode_3: "CAN",
    states: [
      {
        name: "Alberta",
        code: "AB",
      },
      {
        name: "British Columbia",
        code: "BC",
      },
      {
        name: "Manitoba",
        code: "MB",
      },
      {
        name: "New Brunswick",
        code: "NB",
      },
      {
        name: "Newfoundland and Labrador",
        code: "NL",
      },
      {
        name: "Northwest Territories",
        code: "NT",
      },
      {
        name: "Nova Scotia",
        code: "NS",
      },
      {
        name: "Nunavut",
        code: "NU",
      },
      {
        name: "Ontario",
        code: "ON",
      },
      {
        name: "Prince Edward Island",
        code: "PE",
      },
      {
        name: "Quebec",
        code: "QC",
      },
      {
        name: "Saskatchewan",
        code: "SK",
      },
      {
        name: "Yukon",
        code: "YT",
      },
    ],
  },
  {
    name: "Cape Verde",
    callingCode: "+238",
    countryCode_2: "CV",
    countryCode_3: "CPV",
  },
  {
    name: "Cayman Islands",
    callingCode: "+1345",
    countryCode_2: "KY",
    countryCode_3: "CYM",
  },
  {
    name: "Central African Republic",
    callingCode: "+236",
    countryCode_2: "CF",
    countryCode_3: "CAF",
  },
  {
    name: "Chad",
    callingCode: "+235",
    countryCode_2: "TD",
    countryCode_3: "TCD",
  },
  {
    name: "Chile",
    callingCode: "+56",
    countryCode_2: "CL",
    countryCode_3: "CHL",
  },
  {
    name: "China",
    callingCode: "+86",
    countryCode_2: "CN",
    countryCode_3: "CHN",
    states: [
      {
        name: "Anhui",
        code: "34",
      },
      {
        name: "Beijing",
        code: "11",
      },
      {
        name: "Chongqing",
        code: "50",
      },
      {
        name: "Fujian",
        code: "35",
      },
      {
        name: "Gansu",
        code: "62",
      },
      {
        name: "Guangdong",
        code: "44",
      },
      {
        name: "Guangxi",
        code: "45",
      },
      {
        name: "Guizhou",
        code: "52",
      },
      {
        name: "Hainan",
        code: "46",
      },
      {
        name: "Hebei",
        code: "13",
      },
      {
        name: "Heilongjiang",
        code: "23",
      },
      {
        name: "Henan",
        code: "41",
      },
      {
        name: "Hong Kong",
        code: "91",
      },
      {
        name: "Hubei",
        code: "42",
      },
      {
        name: "Hunan",
        code: "43",
      },
      {
        name: "Jiangsu",
        code: "32",
      },
      {
        name: "Jiangxi",
        code: "36",
      },
      {
        name: "Jilin",
        code: "22",
      },
      {
        name: "Liaoning",
        code: "21",
      },
      {
        name: "Macao",
        code: "92",
      },
      {
        name: "Nei Mongol",
        code: "15",
      },
      {
        name: "Ningxia",
        code: "64",
      },
      {
        name: "Qinghai",
        code: "63",
      },
      {
        name: "Shaanxi",
        code: "61",
      },
      {
        name: "Shandong",
        code: "37",
      },
      {
        name: "Shanghai",
        code: "31",
      },
      {
        name: "Shanxi",
        code: "14",
      },
      {
        name: "Sichuan",
        code: "51",
      },
      {
        name: "Taiwan",
        code: "71",
      },
      {
        name: "Tianjin",
        code: "12",
      },
      {
        name: "Xinjiang",
        code: "65",
      },
      {
        name: "Xizang",
        code: "54",
      },
      {
        name: "Yunnan",
        code: "53",
      },
      {
        name: "Zhejiang",
        code: "33",
      },
    ],
  },
  {
    name: "Christmas Island",
    callingCode: "+61",
    countryCode_2: "CX",
    countryCode_3: "CXR",
  },
  {
    name: "Cocos Islands",
    callingCode: "+61",
    countryCode_2: "CC",
    countryCode_3: "CCK",
  },
  {
    name: "Colombia",
    callingCode: "+57",
    countryCode_2: "CO",
    countryCode_3: "COL",
  },
  {
    name: "Comoros",
    callingCode: "+269",
    countryCode_2: "KM",
    countryCode_3: "COM",
  },
  {
    name: "Cook Islands",
    callingCode: "+682",
    countryCode_2: "CK",
    countryCode_3: "COK",
  },
  {
    name: "Costa Rica",
    callingCode: "+506",
    countryCode_2: "CR",
    countryCode_3: "CRI",
  },
  {
    name: "Croatia",
    callingCode: "+385",
    countryCode_2: "HR",
    countryCode_3: "HRV",
  },
  {
    name: "Cuba",
    callingCode: "+53",
    countryCode_2: "CU",
    countryCode_3: "CUB",
  },
  {
    name: "Curacao",
    callingCode: "+599",
    countryCode_2: "CW",
    countryCode_3: "CUW",
  },
  {
    name: "Cyprus",
    callingCode: "+357",
    countryCode_2: "CY",
    countryCode_3: "CYP",
  },
  {
    name: "Czech Republic",
    callingCode: "+420",
    countryCode_2: "CZ",
    countryCode_3: "CZE",
  },
  {
    name: "Democratic Republic of the Congo",
    callingCode: "+243",
    countryCode_2: "CD",
    countryCode_3: "COD",
  },
  {
    name: "Denmark",
    callingCode: "+45",
    countryCode_2: "DK",
    countryCode_3: "DNK",
  },
  {
    name: "Djibouti",
    callingCode: "+253",
    countryCode_2: "DJ",
    countryCode_3: "DJI",
  },
  {
    name: "Dominica",
    callingCode: "+1767",
    countryCode_2: "DM",
    countryCode_3: "DMA",
  },
  {
    name: "Dominican Republic",
    callingCode: "+1",
    countryCode_2: "DO",
    countryCode_3: "DOM",
  }, // changed
  {
    name: "East Timor",
    callingCode: "+670",
    countryCode_2: "TL",
    countryCode_3: "TLS",
  },
  {
    name: "Ecuador",
    callingCode: "+593",
    countryCode_2: "EC",
    countryCode_3: "ECU",
  },
  {
    name: "Egypt",
    callingCode: "+20",
    countryCode_2: "EG",
    countryCode_3: "EGY",
  },
  {
    name: "El Salvador",
    callingCode: "+503",
    countryCode_2: "SV",
    countryCode_3: "SLV",
  },
  {
    name: "Equatorial Guinea",
    callingCode: "+240",
    countryCode_2: "GQ",
    countryCode_3: "GNQ",
  },
  {
    name: "Eritrea",
    callingCode: "+291",
    countryCode_2: "ER",
    countryCode_3: "ERI",
  },
  {
    name: "Estonia",
    callingCode: "+372",
    countryCode_2: "EE",
    countryCode_3: "EST",
  },
  {
    name: "Ethiopia",
    callingCode: "+251",
    countryCode_2: "ET",
    countryCode_3: "ETH",
  },
  {
    name: "Falkland Islands",
    callingCode: "+500",
    countryCode_2: "FK",
    countryCode_3: "FLK",
  },
  {
    name: "Faroe Islands",
    callingCode: "+298",
    countryCode_2: "FO",
    countryCode_3: "FRO",
  },
  {
    name: "Fiji",
    callingCode: "+679",
    countryCode_2: "FJ",
    countryCode_3: "FJI",
  },
  {
    name: "Finland",
    callingCode: "+358",
    countryCode_2: "FI",
    countryCode_3: "FIN",
  },
  {
    name: "France",
    callingCode: "+33",
    countryCode_2: "FR",
    countryCode_3: "FRA",
  },
  {
    name: "French Polynesia",
    callingCode: "+689",
    countryCode_2: "PF",
    countryCode_3: "PYF",
  },
  {
    name: "Gabon",
    callingCode: "+241",
    countryCode_2: "GA",
    countryCode_3: "GAB",
  },
  {
    name: "Gambia",
    callingCode: "+220",
    countryCode_2: "GM",
    countryCode_3: "GMB",
  },
  {
    name: "Georgia",
    callingCode: "+995",
    countryCode_2: "GE",
    countryCode_3: "GEO",
  },
  {
    name: "Germany",
    callingCode: "+49",
    countryCode_2: "DE",
    countryCode_3: "DEU",
  },
  {
    name: "Ghana",
    callingCode: "+233",
    countryCode_2: "GH",
    countryCode_3: "GHA",
  },
  {
    name: "Gibraltar",
    callingCode: "+350",
    countryCode_2: "GI",
    countryCode_3: "GIB",
  },
  {
    name: "Greece",
    callingCode: "+30",
    countryCode_2: "GR",
    countryCode_3: "GRC",
  },
  {
    name: "Greenland",
    callingCode: "+299",
    countryCode_2: "GL",
    countryCode_3: "GRL",
  },
  {
    name: "Grenada",
    callingCode: "+1473",
    countryCode_2: "GD",
    countryCode_3: "GRD",
  },
  {
    name: "Guam",
    callingCode: "+1671",
    countryCode_2: "GU",
    countryCode_3: "GUM",
  },
  {
    name: "Guatemala",
    callingCode: "+502",
    countryCode_2: "GT",
    countryCode_3: "GTM",
  },
  {
    name: "Guernsey",
    callingCode: "+44",
    countryCode_2: "GG",
    countryCode_3: "GGY",
  }, // changed
  {
    name: "Guinea",
    callingCode: "+224",
    countryCode_2: "GN",
    countryCode_3: "GIN",
  },
  {
    name: "Guinea-Bissau",
    callingCode: "+245",
    countryCode_2: "GW",
    countryCode_3: "GNB",
  },
  {
    name: "Guyana",
    callingCode: "+592",
    countryCode_2: "GY",
    countryCode_3: "GUY",
  },
  {
    name: "Haiti",
    callingCode: "+509",
    countryCode_2: "HT",
    countryCode_3: "HTI",
  },
  {
    name: "Honduras",
    callingCode: "+504",
    countryCode_2: "HN",
    countryCode_3: "HND",
  },
  {
    name: "Hong Kong",
    callingCode: "+852",
    countryCode_2: "HK",
    countryCode_3: "HKG",
  },
  {
    name: "Hungary",
    callingCode: "+36",
    countryCode_2: "HU",
    countryCode_3: "HUN",
  },
  {
    name: "Iceland",
    callingCode: "+354",
    countryCode_2: "IS",
    countryCode_3: "ISL",
  },
  {
    name: "India",
    callingCode: "+91",
    countryCode_2: "IN",
    countryCode_3: "IND",
    states: [
      { name: "Andhra Pradesh", code: "AP" },
      { name: "Arunachal Pradesh", code: "AR" },
      { name: "Assam", code: "AS" },
      { name: "Andaman and Nicobar Islands", code: "AN" },
      { name: "Bihar", code: "BR" },
      { name: "Chhattisgarh", code: "CT" },
      { name: "Chandigarh", code: "CH" },
      { name: "Dadar and Nagar Haveli", code: "DN" },
      { name: "Daman and Diu", code: "DD" },
      { name: "Delhi", code: "DL" },
      { name: "Goa", code: "GA" },
      { name: "Gujarat", code: "GJ" },
      { name: "Haryana", code: "HR" },
      { name: "Himachal Pradesh", code: "HP" },
      { name: "Jammu and Kashmir", code: "JK" },
      { name: "Jharkhand", code: "JH" },
      { name: "Karnataka", code: "KA" },
      { name: "Kerala", code: "KL" },
      { name: "Ladakh", code: "LA" },
      { name: "Lakshadeep", code: "LD" },
      { name: "Madya Pradesh", code: "MP" },
      { name: "Maharashtra", code: "MH" },
      { name: "Manipur", code: "MN" },
      { name: "Meghalaya", code: "ML" },
      { name: "Mizoram", code: "MZ" },
      { name: "Nagaland", code: "NL" },
      { name: "Odisha", code: "OR" },
      { name: "Punjab", code: "PB" },
      { name: "Pondicherry", code: "PY" },
      { name: "Rajasthan", code: "RJ" },
      { name: "Sikkim", code: "SK" },
      { name: "Tamil Nadu", code: "TN" },
      { name: "Telangana", code: "TG" },
      { name: "Tripura", code: "TR" },
      { name: "Uttarakhand", code: "UK" },
      { name: "Uttar Pradesh", code: "UP" },
      { name: "West Bengal", code: "WB" },
    ],
  },
  {
    name: "Indonesia",
    callingCode: "+62",
    countryCode_2: "ID",
    countryCode_3: "IDN",
  },
  {
    name: "Iran",
    callingCode: "+98",
    countryCode_2: "IR",
    countryCode_3: "IRN",
  },
  {
    name: "Iraq",
    callingCode: "+964",
    countryCode_2: "IQ",
    countryCode_3: "IRQ",
  },
  {
    name: "Ireland",
    callingCode: "+353",
    countryCode_2: "IE",
    countryCode_3: "IRL",
  },
  {
    name: "Isle of Man",
    callingCode: "+44",
    countryCode_2: "IM",
    countryCode_3: "IMN",
  }, // changed
  {
    name: "Israel",
    callingCode: "+972",
    countryCode_2: "IL",
    countryCode_3: "ISR",
  },
  {
    name: "Italy",
    callingCode: "+39",
    countryCode_2: "IT",
    countryCode_3: "ITA",
    states: [
      {
        name: "Agrigento",
        code: "AG",
      },
      {
        name: "Alessandria",
        code: "AL",
      },
      {
        name: "Ancona",
        code: "AN",
      },
      {
        name: "Aosta",
        code: "AO",
      },
      {
        name: "Arezzo",
        code: "AR",
      },
      {
        name: "Ascoli Piceno",
        code: "AP",
      },
      {
        name: "Asti",
        code: "AT",
      },
      {
        name: "Avellino",
        code: "AV",
      },
      {
        name: "Bari",
        code: "BA",
      },
      {
        name: "Barletta-Andria-Trani",
        code: "BT",
      },
      {
        name: "Belluno",
        code: "BL",
      },
      {
        name: "Benevento",
        code: "BN",
      },
      {
        name: "Bergamo",
        code: "BG",
      },
      {
        name: "Biella",
        code: "BI",
      },
      {
        name: "Bologna",
        code: "BO",
      },
      {
        name: "Bolzano",
        code: "BZ",
      },
      {
        name: "Brescia",
        code: "BS",
      },
      {
        name: "Brindisi",
        code: "BR",
      },
      {
        name: "Cagliari",
        code: "CA",
      },
      {
        name: "Caltanissetta",
        code: "CL",
      },
      {
        name: "Campobasso",
        code: "CB",
      },
      {
        name: "Carbonia-Iglesias",
        code: "CI",
      },
      {
        name: "Caserta",
        code: "CE",
      },
      {
        name: "Catania",
        code: "CT",
      },
      {
        name: "Catanzaro",
        code: "CZ",
      },
      {
        name: "Chieti",
        code: "CH",
      },
      {
        name: "Como",
        code: "CO",
      },
      {
        name: "Cosenza",
        code: "CS",
      },
      {
        name: "Cremona",
        code: "CR",
      },
      {
        name: "Crotone",
        code: "KR",
      },
      {
        name: "Cuneo",
        code: "CN",
      },
      {
        name: "Enna",
        code: "EN",
      },
      {
        name: "Fermo",
        code: "FM",
      },
      {
        name: "Ferrara",
        code: "FE",
      },
      {
        name: "Firenze",
        code: "FI",
      },
      {
        name: "Foggia",
        code: "FG",
      },
      {
        name: "Forli-Cesena",
        code: "FC",
      },
      {
        name: "Frosinone",
        code: "FR",
      },
      {
        name: "Genova",
        code: "GE",
      },
      {
        name: "Gorizia",
        code: "GO",
      },
      {
        name: "Grosseto",
        code: "GR",
      },
      {
        name: "Imperia",
        code: "IM",
      },
      {
        name: "Isernia",
        code: "IS",
      },
      {
        name: "La Spezia",
        code: "SP",
      },
      {
        name: "LAquila L'Aquila",
        code: "AQ",
      },
      {
        name: "Latina",
        code: "LT",
      },
      {
        name: "Lecce",
        code: "LE",
      },
      {
        name: "Lecco",
        code: "LC",
      },
      {
        name: "Livorno",
        code: "LI",
      },
      {
        name: "Lodi",
        code: "LO",
      },
      {
        name: "Lucca",
        code: "LU",
      },
      {
        name: "Macerata",
        code: "MC",
      },
      {
        name: "Mantova",
        code: "MN",
      },
      {
        name: "Massa-Carrara",
        code: "MS",
      },
      {
        name: "Matera",
        code: "MT",
      },
      {
        name: "Medio Campidano",
        code: "VS",
      },
      {
        name: "Messina",
        code: "ME",
      },
      {
        name: "Milano",
        code: "MI",
      },
      {
        name: "Modena",
        code: "MO",
      },
      {
        name: "Monza e Brianza",
        code: "MB",
      },
      {
        name: "Napoli",
        code: "NA",
      },
      {
        name: "Novara",
        code: "NO",
      },
      {
        name: "Nuoro",
        code: "NU",
      },
      {
        name: "Ogliastra",
        code: "OG",
      },
      {
        name: "Olbia-Tempio",
        code: "OT",
      },
      {
        name: "Oristano",
        code: "OR",
      },
      {
        name: "Padova",
        code: "PD",
      },
      {
        name: "Palermo",
        code: "PA",
      },
      {
        name: "Parma",
        code: "PR",
      },
      {
        name: "Pavia",
        code: "PV",
      },
      {
        name: "Perugia",
        code: "PG",
      },
      {
        name: "Pesaro e Urbino",
        code: "PS",
      },
      {
        name: "Pescara",
        code: "PE",
      },
      {
        name: "Piacenza",
        code: "PC",
      },
      {
        name: "Pisa",
        code: "PI",
      },
      {
        name: "Pistoia",
        code: "PT",
      },
      {
        name: "Pordenone",
        code: "PN",
      },
      {
        name: "Potenza",
        code: "PZ",
      },
      {
        name: "Prato",
        code: "PO",
      },
      {
        name: "Ragusa",
        code: "RG",
      },
      {
        name: "Ravenna",
        code: "RA",
      },
      {
        name: "Reggio Calabria",
        code: "RC",
      },
      {
        name: "Reggio Emilia",
        code: "RE",
      },
      {
        name: "Rieti",
        code: "RI",
      },
      {
        name: "Rimini",
        code: "RN",
      },
      {
        name: "Roma",
        code: "RM",
      },
      {
        name: "Rovigo",
        code: "RO",
      },
      {
        name: "Salerno",
        code: "SA",
      },
      {
        name: "Sassari",
        code: "SS",
      },
      {
        name: "Savona",
        code: "SV",
      },
      {
        name: "Siena",
        code: "SI",
      },
      {
        name: "Siracusa",
        code: "SR",
      },
      {
        name: "Sondrio",
        code: "SO",
      },
      {
        name: "Taranto",
        code: "TA",
      },
      {
        name: "Teramo",
        code: "TE",
      },
      {
        name: "Terni",
        code: "TR",
      },
      {
        name: "Torino",
        code: "TO",
      },
      {
        name: "Trapani",
        code: "TP",
      },
      {
        name: "Trento",
        code: "TN",
      },
      {
        name: "Treviso",
        code: "TV",
      },
      {
        name: "Trieste",
        code: "TS",
      },
      {
        name: "Udine",
        code: "UD",
      },
      {
        name: "Varese",
        code: "VA",
      },
      {
        name: "Venezia",
        code: "VE",
      },
      {
        name: "Verbano-Cusio-Ossola",
        code: "VB",
      },
      {
        name: "Vercelli",
        code: "VC",
      },
      {
        name: "Verona",
        code: "VR",
      },
      {
        name: "Vibo Valentia",
        code: "VV",
      },
      {
        name: "Vicenza",
        code: "VI",
      },
      {
        name: "Viterbo",
        code: "VT",
      },
    ],
  },
  {
    name: "Ivory Coast",
    callingCode: "+225",
    countryCode_2: "CI",
    countryCode_3: "CIV",
  },
  {
    name: "Jamaica",
    callingCode: "+1876",
    countryCode_2: "JM",
    countryCode_3: "JAM",
  },
  {
    name: "Japan",
    callingCode: "+81",
    countryCode_2: "JP",
    countryCode_3: "JPN",
    states: [
      {
        name: "Akita",
        code: "5",
      },
      {
        name: "Aomori",
        code: "2",
      },
      {
        name: "Ehime",
        code: "38",
      },
      {
        name: "Gunma",
        code: "10",
      },
      {
        name: "Ibaraki",
        code: "8",
      },
      {
        name: "Iwate",
        code: "3",
      },
      {
        name: "Kagawa",
        code: "37",
      },
      {
        name: "Kanagawa",
        code: "14",
      },
      {
        name: "Kumamoto",
        code: "43",
      },
      {
        name: "Mie",
        code: "24",
      },
      {
        name: "Miyagi",
        code: "4",
      },
      {
        name: "Miyazaki",
        code: "45",
      },
      {
        name: "Nagano",
        code: "20",
      },
      {
        name: "Nagasaki",
        code: "42",
      },
      {
        name: "Nara",
        code: "29",
      },
      {
        name: "Niigata",
        code: "15",
      },
      {
        name: "Okayama",
        code: "33",
      },
      {
        name: "Okinawa",
        code: "47",
      },
      {
        name: "Saga",
        code: "41",
      },
      {
        name: "Saitama",
        code: "11",
      },
      {
        name: "Tottori",
        code: "31",
      },
      {
        name: "Toyama",
        code: "16",
      },
      {
        name: "Wakayama",
        code: "30",
      },
      {
        name: "Yamagata",
        code: "6",
      },
      {
        name: "Aichi",
        code: "23",
      },
      {
        name: "Chiba",
        code: "12",
      },
      {
        name: "Fukui",
        code: "18",
      },
      {
        name: "Fukuoka",
        code: "40",
      },
      {
        name: "Fukushima",
        code: "7",
      },
      {
        name: "Gifu",
        code: "21",
      },
      {
        name: "Hiroshima",
        code: "34",
      },
      {
        name: "Hokkaido",
        code: "1",
      },
      {
        name: "Hyogo",
        code: "28",
      },
      {
        name: "Ishikawa",
        code: "17",
      },
      {
        name: "Kagoshima",
        code: "46",
      },
      {
        name: "Kochi",
        code: "39",
      },
      {
        name: "Kyoto",
        code: "26",
      },
      {
        name: "Oita",
        code: "44",
      },
      {
        name: "Osaka",
        code: "27",
      },
      {
        name: "Shiga",
        code: "25",
      },
      {
        name: "Shimane",
        code: "32",
      },
      {
        name: "Shizuoka",
        code: "22",
      },
      {
        name: "Tochigi",
        code: "9",
      },
      {
        name: "Tokushima",
        code: "36",
      },
      {
        name: "Tokyo",
        code: "13",
      },
      {
        name: "Yamaguchi",
        code: "35",
      },
      {
        name: "Yamanashi",
        code: "19",
      },
    ],
  },
  {
    name: "Jersey",
    callingCode: "+44",
    countryCode_2: "JE",
    countryCode_3: "JEY",
  }, // changed
  {
    name: "Jordan",
    callingCode: "+962",
    countryCode_2: "JO",
    countryCode_3: "JOR",
  },
  {
    name: "Kazakhstan",
    callingCode: "+7",
    countryCode_2: "KZ",
    countryCode_3: "KAZ",
  },
  {
    name: "Kenya",
    callingCode: "+254",
    countryCode_2: "KE",
    countryCode_3: "KEN",
  },
  {
    name: "Kiribati",
    callingCode: "+686",
    countryCode_2: "KI",
    countryCode_3: "KIR",
  },
  {
    name: "Kosovo",
    callingCode: "+383",
    countryCode_2: "XK",
    countryCode_3: "XKX",
  },
  {
    name: "Kuwait",
    callingCode: "+965",
    countryCode_2: "KW",
    countryCode_3: "KWT",
  },
  {
    name: "Kyrgyzstan",
    callingCode: "+996",
    countryCode_2: "KG",
    countryCode_3: "KGZ",
  },
  {
    name: "Laos",
    callingCode: "+856",
    countryCode_2: "LA",
    countryCode_3: "LAO",
  },
  {
    name: "Latvia",
    callingCode: "+371",
    countryCode_2: "LV",
    countryCode_3: "LVA",
  },
  {
    name: "Lebanon",
    callingCode: "+961",
    countryCode_2: "LB",
    countryCode_3: "LBN",
  },
  {
    name: "Lesotho",
    callingCode: "+266",
    countryCode_2: "LS",
    countryCode_3: "LSO",
  },
  {
    name: "Liberia",
    callingCode: "+231",
    countryCode_2: "LR",
    countryCode_3: "LBR",
  },
  {
    name: "Libya",
    callingCode: "+218",
    countryCode_2: "LY",
    countryCode_3: "LBY",
  },
  {
    name: "Liechtenstein",
    callingCode: "+423",
    countryCode_2: "LI",
    countryCode_3: "LIE",
  },
  {
    name: "Lithuania",
    callingCode: "+370",
    countryCode_2: "LT",
    countryCode_3: "LTU",
  },
  {
    name: "Luxembourg",
    callingCode: "+352",
    countryCode_2: "LU",
    countryCode_3: "LUX",
  },
  {
    name: "Macau",
    callingCode: "+853",
    countryCode_2: "MO",
    countryCode_3: "MAC",
  },
  {
    name: "Macao",
    callingCode: "+853",
    countryCode_2: "MO",
    countryCode_3: "MAC",
  },
  {
    name: "Macedonia",
    callingCode: "+389",
    countryCode_2: "MK",
    countryCode_3: "MKD",
  },
  {
    name: "Madagascar",
    callingCode: "+261",
    countryCode_2: "MG",
    countryCode_3: "MDG",
  },
  {
    name: "Malawi",
    callingCode: "+265",
    countryCode_2: "MW",
    countryCode_3: "MWI",
  },
  {
    name: "Malaysia",
    callingCode: "+60",
    countryCode_2: "MY",
    countryCode_3: "MYS",
  },
  {
    name: "Maldives",
    callingCode: "+960",
    countryCode_2: "MV",
    countryCode_3: "MDV",
  },
  {
    name: "Mali",
    callingCode: "+223",
    countryCode_2: "ML",
    countryCode_3: "MLI",
  },
  {
    name: "Malta",
    callingCode: "+356",
    countryCode_2: "MT",
    countryCode_3: "MLT",
  },
  {
    name: "Marshall Islands",
    callingCode: "+692",
    countryCode_2: "MH",
    countryCode_3: "MHL",
  },
  {
    name: "Mauritania",
    callingCode: "+222",
    countryCode_2: "MR",
    countryCode_3: "MRT",
  },
  {
    name: "Mauritius",
    callingCode: "+230",
    countryCode_2: "MU",
    countryCode_3: "MUS",
  },
  {
    name: "Mayotte",
    callingCode: "+262",
    countryCode_2: "YT",
    countryCode_3: "MYT",
  },
  {
    name: "Mexico",
    callingCode: "+52",
    countryCode_2: "MX",
    countryCode_3: "MEX",
    states: [
      {
        name: "Aguascalientes",
        code: "AGU",
      },
      {
        name: "Baja California",
        code: "BCN",
      },
      {
        name: "Baja California Sur",
        code: "BCS",
      },
      {
        name: "Campeche",
        code: "CAM",
      },
      {
        name: "Coahuila",
        code: "COA",
      },
      {
        name: "Colima",
        code: "COL",
      },
      {
        name: "Distrito Federal",
        code: "DIF",
      },
      {
        name: "Durango",
        code: "DUR",
      },
      {
        name: "Guanajuato",
        code: "GUA",
      },
      {
        name: "Guerrero",
        code: "GRO",
      },
      {
        name: "Hidalgo",
        code: "HID",
      },
      {
        name: "Jalisco",
        code: "JAL",
      },
      {
        name: "Michoacan",
        code: "MIC",
      },
      {
        name: "Morelos",
        code: "MOR",
      },
      {
        name: "Nayarit",
        code: "NAY",
      },
      {
        name: "Nuevo Leon",
        code: "NLE",
      },
      {
        name: "Oaxaca",
        code: "OAX",
      },
      {
        name: "Puebla",
        code: "PUE",
      },
      {
        name: "Queretaro",
        code: "QUE",
      },
      {
        name: "Quintana Roo",
        code: "ROO",
      },
      {
        name: "San Luis Potosi",
        code: "SLP",
      },
      {
        name: "Sinaloa",
        code: "SIN",
      },
      {
        name: "Sonora",
        code: "SON",
      },
      {
        name: "Tabasco",
        code: "TAB",
      },
      {
        name: "Tamaulipas",
        code: "TAM",
      },
      {
        name: "Tlaxcala",
        code: "TLA",
      },
      {
        name: "Veracruz",
        code: "VER",
      },
      {
        name: "Yucatan",
        code: "YUC",
      },
      {
        name: "Zacatecas",
        code: "ZAC",
      },
      {
        name: "Chiapas",
        code: "CHP",
      },
      {
        name: "Chihuahua",
        code: "CHH",
      },
      {
        name: "Mexico",
        code: "MEX",
      },
    ],
  },
  {
    name: "Micronesia",
    callingCode: "+691",
    countryCode_2: "FM",
    countryCode_3: "FSM",
  },
  {
    name: "Moldova",
    callingCode: "+373",
    countryCode_2: "MD",
    countryCode_3: "MDA",
  },
  {
    name: "Monaco",
    callingCode: "+377",
    countryCode_2: "MC",
    countryCode_3: "MCO",
  },
  {
    name: "Mongolia",
    callingCode: "+976",
    countryCode_2: "MN",
    countryCode_3: "MNG",
  },
  {
    name: "Montenegro",
    callingCode: "+382",
    countryCode_2: "ME",
    countryCode_3: "MNE",
  },
  {
    name: "Montserrat",
    callingCode: "+1664",
    countryCode_2: "MS",
    countryCode_3: "MSR",
  },
  {
    name: "Morocco",
    callingCode: "+212",
    countryCode_2: "MA",
    countryCode_3: "MAR",
  },
  {
    name: "Mozambique",
    callingCode: "+258",
    countryCode_2: "MZ",
    countryCode_3: "MOZ",
  },
  {
    name: "Myanmar",
    callingCode: "+95",
    countryCode_2: "MM",
    countryCode_3: "MMR",
  },
  {
    name: "Namibia",
    callingCode: "+264",
    countryCode_2: "NA",
    countryCode_3: "NAM",
  },
  {
    name: "Nauru",
    callingCode: "+674",
    countryCode_2: "NR",
    countryCode_3: "NRU",
  },
  {
    name: "Nepal",
    callingCode: "+977",
    countryCode_2: "NP",
    countryCode_3: "NPL",
  },
  {
    name: "Netherlands",
    callingCode: "+31",
    countryCode_2: "NL",
    countryCode_3: "NLD",
  },
  {
    name: "Netherlands Antilles",
    callingCode: "+599",
    countryCode_2: "AN",
    countryCode_3: "ANT",
  },
  {
    name: "New Caledonia",
    callingCode: "+687",
    countryCode_2: "NC",
    countryCode_3: "NCL",
  },
  {
    name: "New Zealand",
    callingCode: "+64",
    countryCode_2: "NZ",
    countryCode_3: "NZL",
  },
  {
    name: "Nicaragua",
    callingCode: "+505",
    countryCode_2: "NI",
    countryCode_3: "NIC",
  },
  {
    name: "Niger",
    callingCode: "+227",
    countryCode_2: "NE",
    countryCode_3: "NER",
  },
  {
    name: "Nigeria",
    callingCode: "+234",
    countryCode_2: "NG",
    countryCode_3: "NGA",
  },
  {
    name: "Niue",
    callingCode: "+683",
    countryCode_2: "NU",
    countryCode_3: "NIU",
  },
  {
    name: "North Korea",
    callingCode: "+850",
    countryCode_2: "KP",
    countryCode_3: "PRK",
  },
  {
    name: "Northern Mariana Islands",
    callingCode: "+1670",
    countryCode_2: "MP",
    countryCode_3: "MNP",
  },
  {
    name: "Norway",
    callingCode: "+47",
    countryCode_2: "NO",
    countryCode_3: "NOR",
  },
  {
    name: "Oman",
    callingCode: "+968",
    countryCode_2: "OM",
    countryCode_3: "OMN",
  },
  {
    name: "Pakistan",
    callingCode: "+92",
    countryCode_2: "PK",
    countryCode_3: "PAK",
  },
  {
    name: "Palau",
    callingCode: "+680",
    countryCode_2: "PW",
    countryCode_3: "PLW",
  },
  {
    name: "Palestine",
    callingCode: "+970",
    countryCode_2: "PS",
    countryCode_3: "PSE",
  },
  {
    name: "Panama",
    callingCode: "+507",
    countryCode_2: "PA",
    countryCode_3: "PAN",
  },
  {
    name: "Papua New Guinea",
    callingCode: "+675",
    countryCode_2: "PG",
    countryCode_3: "PNG",
  },
  {
    name: "Paraguay",
    callingCode: "+595",
    countryCode_2: "PY",
    countryCode_3: "PRY",
  },
  {
    name: "Peru",
    callingCode: "+51",
    countryCode_2: "PE",
    countryCode_3: "PER",
  },
  {
    name: "Philippines",
    callingCode: "+63",
    countryCode_2: "PH",
    countryCode_3: "PHL",
  },
  {
    name: "Pitcairn",
    callingCode: "+64",
    countryCode_2: "PN",
    countryCode_3: "PCN",
  },
  {
    name: "Poland",
    callingCode: "+48",
    countryCode_2: "PL",
    countryCode_3: "POL",
  },
  {
    name: "Portugal",
    callingCode: "+351",
    countryCode_2: "PT",
    countryCode_3: "PRT",
  },
  {
    name: "Puerto Rico",
    callingCode: "+1787, +1939",
    countryCode_2: "PR",
    countryCode_3: "PRI",
  },
  {
    name: "Qatar",
    callingCode: "+974",
    countryCode_2: "QA",
    countryCode_3: "QAT",
  },
  {
    name: "Republic of the Congo",
    callingCode: "+242",
    countryCode_2: "CG",
    countryCode_3: "COG",
  },
  {
    name: "Reunion",
    callingCode: "+262",
    countryCode_2: "RE",
    countryCode_3: "REU",
  },
  {
    name: "Romania",
    callingCode: "+40",
    countryCode_2: "RO",
    countryCode_3: "ROU",
  },
  {
    name: "Russia",
    callingCode: "+7",
    countryCode_2: "RU",
    countryCode_3: "RUS",
  },
  {
    name: "Rwanda",
    callingCode: "+250",
    countryCode_2: "RW",
    countryCode_3: "RWA",
  },
  {
    name: "Saint Barthelemy",
    callingCode: "+590",
    countryCode_2: "BL",
    countryCode_3: "BLM",
  },
  {
    name: "Saint Helena",
    callingCode: "+290",
    countryCode_2: "SH",
    countryCode_3: "SHN",
  },
  {
    name: "Saint Kitts and Nevis",
    callingCode: "+1869",
    countryCode_2: "KN",
    countryCode_3: "KNA",
  },
  {
    name: "Saint Lucia",
    callingCode: "+1758",
    countryCode_2: "LC",
    countryCode_3: "LCA",
  },
  {
    name: "Saint Martin",
    callingCode: "+590",
    countryCode_2: "MF",
    countryCode_3: "MAF",
  },
  {
    name: "Saint Pierre and Miquelon",
    callingCode: "+508",
    countryCode_2: "PM",
    countryCode_3: "SPM",
  },
  {
    name: "Saint Vincent and the Grenadines",
    callingCode: "+1784",
    countryCode_2: "VC",
    countryCode_3: "VCT",
  },
  {
    name: "Samoa",
    callingCode: "+685",
    countryCode_2: "WS",
    countryCode_3: "WSM",
  },
  {
    name: "San Marino",
    callingCode: "+378",
    countryCode_2: "SM",
    countryCode_3: "SMR",
  },
  {
    name: "Sao Tome and Principe",
    callingCode: "+239",
    countryCode_2: "ST",
    countryCode_3: "STP",
  },
  {
    name: "Saudi Arabia",
    callingCode: "+966",
    countryCode_2: "SA",
    countryCode_3: "SAU",
  },
  {
    name: "Senegal",
    callingCode: "+221",
    countryCode_2: "SN",
    countryCode_3: "SEN",
  },
  {
    name: "Serbia",
    callingCode: "+381",
    countryCode_2: "RS",
    countryCode_3: "SRB",
  },
  {
    name: "Seychelles",
    callingCode: "+248",
    countryCode_2: "SC",
    countryCode_3: "SYC",
  },
  {
    name: "Sierra Leone",
    callingCode: "+232",
    countryCode_2: "SL",
    countryCode_3: "SLE",
  },
  {
    name: "Singapore",
    callingCode: "+65",
    countryCode_2: "SG",
    countryCode_3: "SGP",
  },
  {
    name: "Sint Maarten",
    callingCode: "+1721",
    countryCode_2: "SX",
    countryCode_3: "SXM",
  },
  {
    name: "Slovakia",
    callingCode: "+421",
    countryCode_2: "SK",
    countryCode_3: "SVK",
  },
  {
    name: "Slovenia",
    callingCode: "+386",
    countryCode_2: "SI",
    countryCode_3: "SVN",
  },
  {
    name: "Solomon Islands",
    callingCode: "+677",
    countryCode_2: "SB",
    countryCode_3: "SLB",
  },
  {
    name: "Somalia",
    callingCode: "+252",
    countryCode_2: "SO",
    countryCode_3: "SOM",
  },
  {
    name: "South Africa",
    callingCode: "+27",
    countryCode_2: "ZA",
    countryCode_3: "ZAF",
  },
  {
    name: "South Korea",
    callingCode: "+82",
    countryCode_2: "KR",
    countryCode_3: "KOR",
  },
  {
    name: "South Sudan",
    callingCode: "+211",
    countryCode_2: "SS",
    countryCode_3: "SSD",
  },
  {
    name: "Spain",
    callingCode: "+34",
    countryCode_2: "ES",
    countryCode_3: "ESP",
  },
  {
    name: "Sri Lanka",
    callingCode: "+94",
    countryCode_2: "LK",
    countryCode_3: "LKA",
  },
  {
    name: "Sudan",
    callingCode: "+249",
    countryCode_2: "SD",
    countryCode_3: "SDN",
  },
  {
    name: "Suriname",
    callingCode: "+597",
    countryCode_2: "SR",
    countryCode_3: "SUR",
  },
  {
    name: "Svalbard and Jan Mayen",
    callingCode: "+47",
    countryCode_2: "SJ",
    countryCode_3: "SJM",
  },
  {
    name: "Swaziland",
    callingCode: "+268",
    countryCode_2: "SZ",
    countryCode_3: "SWZ",
  },
  {
    name: "Sweden",
    callingCode: "+46",
    countryCode_2: "SE",
    countryCode_3: "SWE",
  },
  {
    name: "Switzerland",
    callingCode: "+41",
    countryCode_2: "CH",
    countryCode_3: "CHE",
  },
  {
    name: "Syria",
    callingCode: "+963",
    countryCode_2: "SY",
    countryCode_3: "SYR",
  },
  {
    name: "Taiwan",
    callingCode: "+886",
    countryCode_2: "TW",
    countryCode_3: "TWN",
  },
  {
    name: "Tajikistan",
    callingCode: "+992",
    countryCode_2: "TJ",
    countryCode_3: "TJK",
  },
  {
    name: "Tanzania",
    callingCode: "+255",
    countryCode_2: "TZ",
    countryCode_3: "TZA",
  },
  {
    name: "Thailand",
    callingCode: "+66",
    countryCode_2: "TH",
    countryCode_3: "THA",
  },
  {
    name: "Togo",
    callingCode: "+228",
    countryCode_2: "TG",
    countryCode_3: "TGO",
  },
  {
    name: "Tokelau",
    callingCode: "+690",
    countryCode_2: "TK",
    countryCode_3: "TKL",
  },
  {
    name: "Tonga",
    callingCode: "+676",
    countryCode_2: "TO",
    countryCode_3: "TON",
  },
  {
    name: "Trinidad and Tobago",
    callingCode: "+1868",
    countryCode_2: "TT",
    countryCode_3: "TTO",
  },
  {
    name: "Tunisia",
    callingCode: "+216",
    countryCode_2: "TN",
    countryCode_3: "TUN",
  },
  {
    name: "Turkey",
    callingCode: "+90",
    countryCode_2: "TR",
    countryCode_3: "TUR",
  },
  {
    name: "Turkmenistan",
    callingCode: "+993",
    countryCode_2: "TM",
    countryCode_3: "TKM",
  },
  {
    name: "Turks and Caicos Islands",
    callingCode: "+1649",
    countryCode_2: "TC",
    countryCode_3: "TCA",
  },
  {
    name: "Tuvalu",
    callingCode: "+688",
    countryCode_2: "TV",
    countryCode_3: "TUV",
  },
  {
    name: "U.S. Virgin Islands",
    callingCode: "+1340",
    countryCode_2: "VI",
    countryCode_3: "VIR",
  },
  {
    name: "Uganda",
    callingCode: "+256",
    countryCode_2: "UG",
    countryCode_3: "UGA",
  },
  {
    name: "Ukraine",
    callingCode: "+380",
    countryCode_2: "UA",
    countryCode_3: "UKR",
  },
  {
    name: "United Arab Emirates",
    callingCode: "+971",
    countryCode_2: "AE",
    countryCode_3: "ARE",
  },
  {
    name: "United Kingdom",
    callingCode: "+44",
    countryCode_2: "GB",
    countryCode_3: "GBR",
    // states: [
    //   { name: "Channel Islands", code: "GB-CHA" },
    //   { name: "England", code: "GB-ENG" },
    //   { name: "Isle of Man", code: "GB-IOM" },
    //   { name: "Northern Ireland", code: "GB-NIR" },
    //   { name: "Scotland", code: "GB-SCT" },
    //   { name: "Wales", code: "GB-WLS" },
    // ],
  },
  {
    name: "United States",
    callingCode: "+1",
    countryCode_2: "US",
    countryCode_3: "USA",
    states: [
      { name: "Alabama", code: "AL" },
      { name: "Alaska", code: "AK" },
      { name: "American Samoa", code: "AS" },
      { name: "Arizona", code: "AZ" },
      { name: "Arkansas", code: "AR" },
      { name: "California", code: "CA" },
      { name: "Colorado", code: "CO" },
      { name: "Connecticut", code: "CT" },
      { name: "Delaware", code: "DE" },
      { name: "District of Columbia", code: "DC" },
      { name: "Florida", code: "FL" },
      { name: "Georgia", code: "GA" },
      { name: "Guam", code: "GU" },
      { name: "Hawaii", code: "HI" },
      { name: "Idaho", code: "ID" },
      { name: "Illinois", code: "IL" },
      { name: "Indiana", code: "IN" },
      { name: "Iowa", code: "IA" },
      { name: "Kansas", code: "KS" },
      { name: "Kentucky", code: "KY" },
      { name: "Louisiana", code: "LA" },
      { name: "Maine", code: "ME" },
      { name: "Maryland", code: "MD" },
      { name: "Massachusetts", code: "MA" },
      { name: "Michigan", code: "MI" },
      { name: "Minnesota", code: "MN" },
      { name: "Mississippi", code: "MS" },
      { name: "Missouri", code: "MO" },
      { name: "Montana", code: "MT" },
      { name: "Nebraska", code: "NE" },
      { name: "Nevada", code: "NV" },
      { name: "New Hampshire", code: "NH" },
      { name: "New Jersey", code: "NJ" },
      { name: "New Mexico", code: "NM" },
      { name: "New York", code: "NY" },
      { name: "North Carolina", code: "NC" },
      { name: "North Dakota", code: "ND" },
      { name: "Northern Mariana Islands", code: "MP" },
      { name: "Ohio", code: "OH" },
      { name: "Oklahoma", code: "OK" },
      { name: "Oregon", code: "OR" },
      { name: "Pennsylvania", code: "PA" },
      { name: "Puerto Rico", code: "PR" },
      { name: "Rhode Island", code: "RI" },
      { name: "South Carolina", code: "SC" },
      { name: "South Dakota", code: "SD" },
      { name: "Tennessee", code: "TN" },
      { name: "Texas", code: "TX" },
      { name: "United States Minor Outlying Islands", code: "UM" },
      { name: "Utah", code: "UT" },
      { name: "Vermont", code: "VT" },
      { name: "Virgin Islands, U.S.", code: "VI" },
      { name: "Virginia", code: "VA" },
      { name: "Washington", code: "WA" },
      { name: "West Virginia", code: "WV" },
      { name: "Wisconsin", code: "WI" },
      { name: "Wyoming", code: "WY" },
    ],
  },
  {
    name: "Uruguay",
    callingCode: "+598",
    countryCode_2: "UY",
    countryCode_3: "URY",
  },
  {
    name: "Uzbekistan",
    callingCode: "+998",
    countryCode_2: "UZ",
    countryCode_3: "UZB",
  },
  {
    name: "Vanuatu",
    callingCode: "+678",
    countryCode_2: "VU",
    countryCode_3: "VUT",
  },
  {
    name: "Vatican",
    callingCode: "+379",
    countryCode_2: "VA",
    countryCode_3: "VAT",
  },
  {
    name: "Venezuela",
    callingCode: "+58",
    countryCode_2: "VE",
    countryCode_3: "VEN",
  },
  {
    name: "Vietnam",
    callingCode: "+84",
    countryCode_2: "VN",
    countryCode_3: "VNM",
  },
  {
    name: "Wallis and Futuna",
    callingCode: "+681",
    countryCode_2: "WF",
    countryCode_3: "WLF",
  },
  {
    name: "Western Sahara",
    callingCode: "+212",
    countryCode_2: "EH",
    countryCode_3: "ESH",
  },
  {
    name: "Yemen",
    callingCode: "+967",
    countryCode_2: "YE",
    countryCode_3: "YEM",
  },
  {
    name: "Zambia",
    callingCode: "+260",
    countryCode_2: "ZM",
    countryCode_3: "ZMB",
  },
  {
    name: "Zimbabwe",
    callingCode: "+263",
    countryCode_2: "ZW",
    countryCode_3: "ZWE",
  },
];
