export const environment = {
  production: false,
  dev: true,
  mocked_all: false,
  mocked_content: true,
  mocked_endpoints: false,
  is_rt4_be: true,
  rt4_modify_flow: true,
  portal_subdomain: "",
  property_code: "043241",
  load_vwo_domain_relace_script: true,
  home_page:
    "http://mbs-be-qa1.ttaws.com.s3-website-ap-southeast-1.amazonaws.com",
  path_prefix: "https://rt4qa.reztrip.io/rottnest",
  ui_logging_endpoint: "https://rt4qa.reztrip.io/rottnest/clientLogs",
  ip_address_endpoint: "https://ipapi.co/json",
  proxy_path_prefix: "",
  tealiumScriptSrc1: "",
  tealiumScriptSrc2: "",
  rateMatchScript: "",
  VWOScriptSrc1: "",
  derbyTagUrl: "",
  derbyTagAccountCode: "",
  derbyTagHotelCode: "",
  trip_tease_client_key: "",
  trip_tease_hotel_key: "",
  trip_tease_class_name: "",
  calendar_max_load_months: 13,
  custom_scripts_path: "https://dkbg7t9x5nwac.cloudfront.net",
  isMCPEnabled: false,
  calendarStartOnSunday: true,
  optimizelySDKKey: "HmNpwnWS1KjxXMkQmcP1R",
  enableRollbar: true,
  envType: "qa", // can be dev, qa, uat, prod
  envName: "qa",
  rollbarToken: "f7fcccb9ae7c4b5d803946fad636116e",
};
